# Generated by Django 4.2.5 on 2023-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_client_alter_event_contract_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="client",
        ),
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
