# Generated by Django 4.2.5 on 2023-09-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_support_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="events.eventstatus",
            ),
        ),
    ]
