# Generated by Django 4.2.5 on 2023-09-28 15:10

from django.db import migrations


def create_event_status_instances(apps, schema_editor):
    # Create an instance for each event status,
    # so that events can be created with a status
    EventStatus = apps.get_model("events", "EventStatus")

    STATUS_CHOICES = [
        ("CRE", "Created"),
        ("PRO", "In Process"),
        ("END", "Ended"),
    ]

    for status_code, status_name in STATUS_CHOICES:
        EventStatus.objects.create(status=status_code)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_status"),
    ]

    operations = [
        migrations.RunPython(create_event_status_instances),
    ]
