# Generated by Django 4.2.5 on 2023-10-05 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_auto_20230928_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventstatus",
            options={"verbose_name_plural": "statuses"},
        ),
    ]
