# Generated by Django 4.2.5 on 2023-10-05 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_eventstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventstatus",
            options={"verbose_name_plural": "event statuses"},
        ),
    ]
