# Generated by Django 4.2.5 on 2023-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractstatus",
            name="status",
            field=models.CharField(
                choices=[("UNS", "Not Signed"), ("SIG", "Signed"), ("PYD", "Payed")],
                max_length=3,
                unique=True,
            ),
        ),
    ]
