# Generated by Django 4.2.5 on 2023-09-22 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_alter_contractstatus_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="Payment_due",
            new_name="payment_due",
        ),
    ]
