# Generated by Django 4.2.5 on 2023-09-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0004_rename_payment_due_contract_payment_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contracts.contractstatus",
            ),
        ),
    ]
