# Generated by Django 4.2.5 on 2023-09-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_client_company_name_alter_client_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.clientstatus",
            ),
        ),
        migrations.AlterField(
            model_name="clientstatus",
            name="status",
            field=models.CharField(
                choices=[("PRO", "Prospective Client"), ("EXI", "Existing Client")],
                default="PRO",
                max_length=3,
                unique=True,
            ),
        ),
    ]
