# Generated by Django 4.2.5 on 2023-09-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_alter_client_status_alter_clientstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="clients.clientstatus"
            ),
        ),
    ]
