# Generated by Django 4.2.5 on 2023-09-28 15:04

from django.db import migrations


def create_client_status_instances(apps, schema_editor):
    # Create an instance for each client status,
    # so that clients can be created with a status
    ClientStatus = apps.get_model("clients", "ClientStatus")

    STATUS_CHOICES = [
        ("PRO", "Prospective Client"),
        ("EXI", "Existing Client"),
    ]

    for status_code, status_name in STATUS_CHOICES:
        ClientStatus.objects.create(status=status_code)


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_alter_client_status"),
    ]

    operations = [
        migrations.RunPython(create_client_status_instances),
    ]
