# Generated by Django 4.2.5 on 2023-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_auto_20230928_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=25),
        ),
    ]
