# Generated by Django 4.2.5 on 2023-10-05 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_clientstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientstatus",
            options={"verbose_name_plural": "client statuses"},
        ),
    ]
