# Generated by Django 4.2.5 on 2023-09-14 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_userrole_user_date_created_user_date_updated_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
